# Generated by Django 2.1.7 on 2019-03-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
